"""init

Revision ID: d4620670f801
Revises: 
Create Date: 2026-08-21 00:40:28.320305

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "d4620670f801"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
