"""add suite_prompt_links table

Revision ID: e83e30762832
Revises: cb2ee654922e
Create Date: 2026-08-30 02:18:16.459976

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e83e30762832"
down_revision: Union[str, Sequence[str], None] = "cb2ee654922e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "suite_prompt_links",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("suite_id", sa.UUID(), nullable=False),
        sa.Column("prompt_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["prompt_id"], ["prompts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["suite_id"], ["test_suites.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("suite_id", "prompt_id", name="uq_suite_prompt"),
    )
    op.create_index(
        op.f("ix_suite_prompt_links_prompt_id"),
        "suite_prompt_links",
        ["prompt_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_suite_prompt_links_suite_id"),
        "suite_prompt_links",
        ["suite_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_suite_prompt_links_suite_id"), table_name="suite_prompt_links"
    )
    op.drop_index(
        op.f("ix_suite_prompt_links_prompt_id"), table_name="suite_prompt_links"
    )
    op.drop_table("suite_prompt_links")
    # ### end Alembic commands ###
